### ISSUE TITLE
Allow to avoid instance_exec if user needs it in hook

### ISSUE THREAD

**Issue by JelF** [nulldef/statum#8]
instance_exec is a good default behaviour, but user may want to use another scope. Best idea is allow 
`after: -> (instance) { instance.foo! }` syntax.

It also convenient for rails users

This depends on #4 and i can fix it there

**Comment by nulldef** [comment]
Yes, let pass instance into user's hooks always, It seemd to be logical. Can you do it in #4?

**Comment by JelF** [comment]
> let pass instance into user's hooks always

It would fuck up lambdas like `-> {}`
It is also less convenient

**Comment by nulldef** [comment]
closed by #9
